# Generated by Django 4.1.2 on 2022-11-13 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Full name')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('state', models.CharField(max_length=100, verbose_name='State')),
                ('zipcode', models.CharField(max_length=12, verbose_name='ZIP code')),
                ('basketball', models.BooleanField()),
                ('football', models.BooleanField()),
                ('baseball', models.BooleanField()),
                ('volleyball', models.BooleanField()),
                ('tennis', models.BooleanField()),
                ('handball', models.BooleanField()),
                ('cricket', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Park',
                'verbose_name_plural': 'Parks',
            },
        ),
    ]
